### PR TITLE
update reviewdog and introduce depup workflow

### LINKED ISSUE #296: Update reviewdog for our action
Related https://github.com/wemake-services/wemake-python-styleguide/issues/1698

### PR DESCRIPTION
**Pull request by skarzi**
# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [ ] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [x] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #296

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]
Thanks, but I guess that it will still fail as in `wemake-python-styleguide` 😞

**Comment by skarzi** [comment]
Ahh sorry for that. I think it's related to https://github.com/haya14busa/action-depup/issues/17
I will correct depup workflow when before mentioned issue will be resolved

**Comment by rickstaa** [comment]
@sobolevn Can you check if [action-depup/pull/21] (https://github.com/reviewdog/action-depup/pull/21) solves the issue your having?

**Comment by sobolevn** [comment]
@rickstaa it is still failing. But with new error:

```
Target repository set to wemake-services/dotenv-linter
Pull request branch to create or update set to 'depup/reviewdog'
Configured git committer as 'GitHub <noreply@github.com>'
Configured git author as 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
Pull request branch 'depup/reviewdog' does not exist yet
Branch 'depup/reviewdog' is not ahead of base 'master' and will not be created
/usr/bin/git config --local --add http.https://github.com/.extraheader AUTHORIZATION: basic ***
```

**Comment by sobolevn** [comment]
Looks like that it is fixed now. Thanks! 
https://github.com/wemake-services/dotenv-linter/pull/301

**Comment by rickstaa** [comment]
Good to hear! Don't hesitate to let us know if you experience any other problems.

**Pull request merged**
