### PR TITLE
remove quoting from GitHub actions Dockerfile entrypoint

### LINKED ISSUE #224: GitHub action linting multiple dotenv files
# Bug report

Hello :wave: 

first of all thanks for another awesome project!

## What's wrong

I have troubles with GitHub action when `options` is list of files.
In one of my projects I have multiple dotenv files stored in multiple directories, something like:

```
.envs/
  .webserver/
    .something
  .worker/
    .something_else
```

so I wanted to use `find` and `paste` combination to create output with string being space separated list of all dotenv files that I want to lint. 
I have also checked that passing such string to `options` input directly like listed in docs and below fails.

```
...
 with:
    options: '.envs/.webserver/.something .envs/.webserver/.something_else'
```

It probably doesn't work because in [`entrypoint.sh`](https://github.com/wemake-services/dotenv-linter/blob/03e4b305ad31da59c7142243df98d9fad955eebc/scripts/entrypoint.sh#L13) -  `  output=$(dotenv-linter "$INPUT_OPTIONS")` is quoted to prevent globbing (if I understand correctly), but this also feeds `dotenv-liter` command with *one* argument that is regular string, something like:

```bash
dotenv-linter ".envs/.webserver/.something .envs/.webLinting options: .envs/.dist/.slave-1 .envs/.dist/.master .envs/.dist/.slave-2
11
server/.something_else"
```

so the command fails with following output:

```
Error: Invalid value for "files": Path ".envs/.webserver/.something .envs/.webserver/.something_else .envs/.worker/.something" does not exist.
```

## How is that should be

It should work properly as described in docs.
When I remove quotes in `entrypoint.sh` getting - `$(dotenv-linter $INPUT_OPTIONS)` it works as expected, however it expands globs, which may be undesired behaviour.

## System information

GitHub actions runs on `ubuntu-latest`. However I have also tested it by building image and running command inside it locally.
If it will be helpful I can prepare some simple failing example later on this week.

### flake8 information

Contents of `flake8 --bug-report`:

### pip information

Contents of `pip freeze`:

### PR DESCRIPTION
**Pull request by skarzi**
Add new step to `dotenv.yml` workflow that lint multiple files.

# I have made things!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc)
- [x] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Related issues

Closes #224

### CODE REVIEW

**Comment by sobolevn** [comment]
@skarzi looks like there's something wrong:

> Error: Invalid value for "files": Path "tests/fixtures/.env.correct tests/fixtures/.env.duplicate" does not exist.

**Comment by skarzi** [comment]
that's exactly the error I have posted in #224 
And this step fails, because it uses action `dotenv-linter@master` (from `master` branch)

**Comment by skarzi** [comment]
this is also new step added by me, to test if linting multiple files in GitHub actions works properly

**Comment by sobolevn** [comment]
Oh, I get it now! Thanks a lot for the fix!

**Pull request merged**
